{
	"id": 200170196,
	"url": "https://cloudflare.zendesk.com/api/v2/help_center/en-us/articles/200170196.json",
	"html_url": "https://cloudflare.zendesk.com/hc/en-us/articles/200170196-Responding-to-DDoS-attacks",
	"author_id": 18409122867,
	"comments_disabled": true,
	"draft": false,
	"promoted": false,
	"position": 0,
	"section_id": 360007347692,
	"created_at": "2013-06-12T18:22:42Z",
	"name": "Responding to DDoS attacks",
	"title": "Responding to DDoS attacks",
	"source_locale": "en-us",
	"locale": "en-us",
	"outdated": false,
	"outdated_locales": [],
	"edited_at": "2022-07-25T13:27:41Z",
	"user_segment_id": null,
	"permission_group_id": 1706732,
	"content_tag_ids": [],
	"label_names": [
		"ddos",
		"advanced_ddos_in_app",
		"attack",
		"dash-troubleshooting",
		"under attack",
		"advanced ddos in app",
		"under attack mode",
		"troubleshoot",
		"ransom",
		"mitigate"
	],
	"user_segment_ids": []
}
